name: Build and push image
on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - wgcf-connector.sh
  workflow_dispatch:
  
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
  
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          
      - name: Login to Container Registry
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_REPOSITORY_OWNER --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build image
        run: docker build . -t ghcr.io/${GITHUB_REPOSITORY,,}:latest
        
      - name: Push image
        run: docker push ghcr.io/${GITHUB_REPOSITORY,,}:latest